# 1 "/home/quanghaictu/intern/Ai-Thinker-WB2/datic/components/hardware/button/button.c"
# 1 "/home/quanghaictu/intern/Ai-Thinker-WB2/datic/build_out/button//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/home/quanghaictu/intern/Ai-Thinker-WB2/datic/components/hardware/button/button.c"
