# 1 "/home/dinhquangha/Ai-Thinker-WB2/components/network/ble/blestack/src/cli_cmds/pts_cli_cmds.c"
# 1 "/home/dinhquangha/Ai-Thinker-WB2/datic/build_out/blestack//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/home/dinhquangha/Ai-Thinker-WB2/components/network/ble/blestack/src/cli_cmds/pts_cli_cmds.c"
